site_name: My Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
    scheme: default

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.share
    - header.autohide
    - content.code.annotate
    - content.typography.unicode
    - content.tabs.link
    - content.comments
    - codehilitetheme.material

plugins:
  - search
  - macros
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

  - git-revision-date-localized:
      type: date
      locale: en
      fallback_to_build_date: true

  - section-index:
      toc_level: 2
      toc_expand: false
      auto_section_number: true

  - pdf-export:
      verbose: true
      author: liu15210520737
      copyright: liu15210520737
      toc_depth: 2
      cover_title: My Docs
      cover_subtitle: My Docs
      cover_logo: logo.png
      cover_author: liu15210520737
      cover_date: true
      page_numbers: true
      toc_title: Table of Contents
      toc_depth: 2
      exclude_pages:
        - index.md
        - about.md
        - contact.md
        - blog.md
        - blog2.md
        - sub11.md
        - sub12.md
        - sub21.md
        - sub22.md
        - toc.md
        - txt.md
        - pdf.md
        - docx.md
        - xlsx.md
        - pptx.md
        - img.md
        - video.md
        - audio.md
        - code.md
        - link.md
        - math.md
        - table.md
        - quote.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      use_pygments: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

  - Blog: blog.md
  - Blog2: blog2.md

  - Sub1:
    - Sub11: sub11.md
    - Sub12: sub12.md

  - Sub2:
    - Sub21: sub21.md
    - Sub22: sub22.md


  - toc: toc.md

  - txt: txt.md
  - pdf: pdf.md
  - docx: docx.md
  - xlsx: xlsx.md
  - pptx: pptx.md

  - img: img.md
  
  - video: video.md  

  
  - audio: audio.md


  - code: code.md
  

  - link: link.md


  - math: math.md


  - table: table.md


  - quote: quote.md