site_name: My Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
    scheme: default

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.share
    - header.autohide
    - content.code.annotate
    - content.typography.unicode
    - content.tabs.link
    - content.comments
    - codehilitetheme.material

plugins:
  - search
  - macros:
      module_name: macros

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

  - git-revision-date-localized:
      type: date
      locale: en_US
      fallback_to_build_date: true

  - section-index:
      toc_level: 2
      toc_expand: false
      auto_section_number: true

  - pdf-export:
      verbose: true
      author: liu15210520737
      copyright: liu15210520737
      toc_depth: 2
      cover_title: My Docs
      cover_subtitle: My Docs
      cover_logo: logo.png
      cover_page_number: true
      cover_first_page: true
      cover_last_page: true
      page_numbers: true
      break_level: 2
      break_side: even
      break_first_page: true
      break_last_page: true
      break_blank_page: true
      break_header_footer: true
      break_font_size: 12
      break_font_color: black
      break_font_family: Arial
      break_header_left: My Docs
      break_header_center: Page
      break_header_right: {{ page_number }}
      break_footer_left: {{ page_number }}
      break_footer_center: My Docs
      break_footer_right: {{ page_number }}
      break_footer_spacing: 10
      break_footer_font_size: 12
      break_footer_font_color: black
      break_footer_font_family: Arial
      break_background_color: white
      break_background_image: background.png
      break_background_position: center
      break_background_repeat: no-repeat
      break_background_size: cover
      break_background_opacity: 1.0
      break_header_font_size: 12
      break_header_font_color: black
      break_header_font_family: Arial
      break_header_spacing: 10
      break_header_line: true
      break_header_line_color: black
      break_header_line_width: 1
      break_footer_line: true
      break_footer_line_color: black
      break_footer_line_width: 1
      break_page_margin: 20
      break_page_size: A4
      break_page_orientation: portrait
      break_page_header: ''
      break_page_footer: ''
      break_page_header_spacing: 10
      break_page_footer_spacing: 10
      break_page_header_font_size: 12
      break_page_header_font_color: black
      break_page_header_font_family: Arial
      break_page_header_line: true
      break_page_header_line_color: black
      break_page_header_line_width: 1
      break_page_footer_font_size: 12
      break_page_footer_font_color: black
      break_page_footer_font_family: Arial
      break_page_footer_line: true
      break_page_footer_line_color: black
      break_page_footer_line_width: 1

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      use_pygments: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

  - Blog: blog.md
  - Blog2: blog2.md

  - Sub1:
    - Sub11: sub11.md
    - Sub12: sub12.md

  - Sub2:
    - Sub21: sub21.md
    - Sub22: sub22.md


  - toc: toc.md

  - txt: txt.md
  - pdf: pdf.md
  - docx: docx.md
  - xlsx: xlsx.md
  - pptx: pptx.md

  - img: img.md
  
  - video: video.md  

  
  - audio: audio.md


  - code: code.md
  

  - link: link.md


  - math: math.md


  - table: table.md


  - quote: quote.md